### ISSUE TITLE
PolicyMode parameter not effective

### ISSUE THREAD

**Issue by Daniel-t** [jklotzsche-msft/PS.MTA-STS#15]
#13 not resolved as the PolicyMode parameter is not used to change the policy file.

Due to this line being commented out
https://github.com/jklotzsche-msft/PS.MTA-STS/blob/93d559fe85245214335bd4c3fbee027053d33c9a/PS.MTA-STS/functions/New-PSMTASTSFunctionAppDeployment.ps1#L215

**Comment by jklotzsche-msft** [comment]
is fixed already. Will be published with the new version today.
