### ISSUE TITLE
App Service Plan parameter

### ISSUE THREAD

**Issue by WiltshireKate** [jklotzsche-msft/PS.MTA-STS#17]
Please can the function "New-PSMTASTSFunctionAppDeployment" be updated to allow an App Service Plan name to be provided (for either creation, or to use an existing one).

As it stands, it creates an App Service Plan named for the region, which gets confusing if you have a lot...

I have moved the FunctionApp to a new consumption App Service Plan named as per our organisation standard - I assume this will this not cause any issues with the update function in PS.MTA-STS?

Thanks
Kate

**Comment by jklotzsche-msft** [comment]
Hi @WiltshireKate, thank you for the information. We will add this parameter in the next version of the module.

Yes, it doesn't cause any issues, if you move an app to another app service plan. There is even an [documentation from Microsoft on how to do so](https://learn.microsoft.com/en-us/azure/app-service/app-service-plan-manage#move-an-app-to-another-app-service-plan). If you follow the instructions, this is fine.

**Comment by jklotzsche-msft** [comment]
new "PlanName" parameter implemented and tested. Will be published with next version

**Comment by jklotzsche-msft** [comment]
added for release in version 1.2.2
