### ISSUE TITLE
Errors in New-PSMTASTSFunctionAppDeployment

### ISSUE THREAD

**Issue by BohrenAn** [jklotzsche-msft/PS.MTA-STS#2]
###################################################################
ERROR1: Function Name is not unique - Azure Storage is created anyway.
###################################################################
New-PSMTASTSFunctionAppDeployment -Location "westeurope" -ResourceGroupName "RG_MTASTS" -FunctionAppName "func-PSMTASTS" -StorageAccountName "mtastsicewolfch"
New-PSMTASTSFunctionAppDeployment : Function name 'func-PSMTASTS' is not available.  Please try a different name.       At line:1 char:1                                                                                                        + New-PSMTASTSFunctionAppDeployment -Location "westeurope" -ResourceGro ...                                             + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                     + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException                                          + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,New-PSMTASTSFunctionAppDeployment       
New-PSMTASTSFunctionAppDeployment : Cannot bind argument to parameter 'Path' because it is null.
At line:1 char:1
+ New-PSMTASTSFunctionAppDeployment -Location "westeurope" -ResourceGro ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [New-PSMTASTSFunctionAppDeployment], ParameterBindingValidationExceptio
   n
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,New-PSMTASTSFunctionAppDeployment

###################################################################
ERROR2 - Is a subsequent Error of ERROR1
###################################################################
New-PSMTASTSFunctionAppDeployment -Location "westeurope" -ResourceGroupName "RG_MTASTS" -FunctionAppName "PSMTASTS-ICEWOLFCH" -StorageAccountName "mtastsicewolfch"
New-PSMTASTSFunctionAppDeployment : The storage account named mtastsicewolfch is already taken.
Parameter name: Name
At line:1 char:1
+ New-PSMTASTSFunctionAppDeployment -Location "westeurope" -ResourceGro ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,New-PSMTASTSFunctionAppDeployment

###################################################################
ERROR3 - Error in Function New-PSMTASTSFunctionAppDeployment
###################################################################
Seems that all Azure Resources have been deployed
![image](https://github.com/jklotzsche-msft/PS.MTA-STS/assets/45082822/851121ac-0123-47a2-bf8e-f3e8854c310a)

New-PSMTASTSFunctionAppDeployment -Location "westeurope" -ResourceGroupName "RG_MTASTS" -FunctionAppName "PSMTASTS-ICEWOLFCH" -StorageAccountName "mtastsicewolf"
New-PSMTASTSFunctionAppDeployment : An object at the specified path C:\Users\A9BB6~1.BOH does not exist.
At line:1 char:1
+ New-PSMTASTSFunctionAppDeployment -Location "westeurope" -ResourceGro ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,New-PSMTASTSFunctionAppDeployment

Remove-Item : An object at the specified path C:\Users\A9BB6~1.BOH does not exist.
At C:\Users\a.bohren\OneDrive - Icewolf\Dokumente\WindowsPowerShell\Modules\PS.MTA-STS\1.1.2\PS.MTA-STS.psm1:496
char:25
+ ...           $null = Remove-Item -Path $workingDirectory -Recurse -Force
+                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Remove-Item], PSArgumentException
    + FullyQualifiedErrorId : Argument,Microsoft.PowerShell.Commands.RemoveItemCommand

Kind Regards
Andres

**Comment by jklotzsche-msft** [comment]
added by @BohrenAn. Thank you very much for contributing to this project!
