### ISSUE TITLE
Remove AzureWebJobsDashboard App setting

### ISSUE THREAD

**Issue by WiltshireKate** [jklotzsche-msft/PS.MTA-STS#24]
Hi.
An error is being reported because AzureWebJobsDashboard built-in logging was auto-enabled, which is deprecated and only supported on version 1.x of the Azure Functions runtime.
As the Function App is on runtime version ~4 and Application Insights was also set up automatically, the AzureWebJobsDashboard App setting can be removed.
Either the code should be updated or a note added to the instructions to remove it manually.
Cheers :)

**Comment by jklotzsche-msft** [comment]
As described in [Functions App Settings](https://learn.microsoft.com/en-us/azure/azure-functions/functions-app-settings#azurewebjobsdashboard), the AzureWebJobsDashboard app settings is deprecated and will automatically be removed in future deployments of the function app.

Thank you @WiltshireKate for pointing out!

**Comment by jklotzsche-msft** [comment]
As described in ["Functions App Settings"](https://learn.microsoft.com/en-us/azure/azure-functions/functions-app-settings#azurewebjobsdashboard), the AzureWebJobsDashboard app settings is deprecated and will automatically be removed in future deployments of the function app.

Thank you @WiltshireKate for pointing out!
