### ISSUE TITLE
Classic Application Insights was retired on February 29, 2024

### ISSUE THREAD

**Issue by BohrenAn** [jklotzsche-msft/PS.MTA-STS#34]
Hi Jamy,

I've got a warning on the Application Insights

<img width="1028" alt="image" src="https://github.com/user-attachments/assets/9526a8e8-004e-422f-80bb-c7f567a45f68">

https://azure.microsoft.com/en-us/updates/we-re-retiring-classic-application-insights-on-29-february-2024/ 

Kind Regards
Andres

**Comment by BohrenAn** [comment]
Proposal:
Use the -DisableApplicationInsights Parameter of New-AzFunctionApp.
You can still use the Metrics of the last 30 Days in the Function App
@jklotzsche-msft You agree?

**Comment by jklotzsche-msft** [comment]
@BohrenAn, I suggest to add a note in the docs about it, but leave application insights enabled. According to your screenshot, the classic resources will be migrated automatically. Therefore, I would like to keep it as is. You agree?
Anyways, I will add an additional parameter for "New-PSMTASTSFunctionAppDeployment", where you can choose to disable application insighs as suggested.

**Comment by jklotzsche-msft** [comment]
changes will be published with new version 1.3.0 shortly
