### ISSUE TITLE
Upgrade Function Runtime to PowerShell 7.4

### ISSUE THREAD

**Issue by BohrenAn** [jklotzsche-msft/PS.MTA-STS#35]
Anounced here
https://github.com/Azure/azure-functions-powershell-worker/wiki/Upgrading-your-Azure-Function-Apps-to-run-on-PowerShell-7.4

**Comment by dreamaker69** [comment]
I pulled a change in a doc. ;)

**Comment by jklotzsche-msft** [comment]
Upgraded Function Runtime to PowerShell 7.4 in docs and automatic deployment. Will be part of the next version of the project
