### ISSUE TITLE
If CNAME check fails, please give option to still add custom domain and certificate

### ISSUE THREAD

**Issue by peterb-bne** [jklotzsche-msft/PS.MTA-STS#43]
If the CNAME check fails, Add-PSMTASTSCustomDomain displays a warning message, and does not add the custom domain or certificate.  We would like to have the option to add the custom domain and certificate regardless of whether the CNAME records exists or not as there is no dependency.  This would allow us to set up function apps for the 3 states in advance, and then people can control which policy they want to use by updating their CNAME record.

**Comment by BohrenAn** [comment]
Hi @peterb-bne 

It's not possible via Azure Portal
![image](https://github.com/user-attachments/assets/91f9ba3d-4be3-4a56-af97-171fa53f90e0)

Nor with PowerShell

![image](https://github.com/user-attachments/assets/a87d1078-df3c-46cf-a717-27ffcd8d426c)

Kind Regards
Andres
