### ISSUE TITLE
DNS Server in Export-PSMTASTSDomainsFromExo

### ISSUE THREAD

**Issue by gbeisser** [jklotzsche-msft/PS.MTA-STS#9]
In case the DNS server 8.8.8.8 used as the default in the function is not accessible (e.g. corporate network) the script is very long running (without errors) and  leads to incorrect results.  (WARNING: MX Record does not point to Exchange Online (only)). The DNS server used by the system should be used as the default. (but configurable if required)

**Comment by jklotzsche-msft** [comment]
@gbeisser, many thanks for the input.

The DNS server must be an external/public one to make sure that an internal, corporate DNS Server does not return its own, internal records. Therefore, 8.8.8.8 was used as a default and you can already change it using the "-DNSServer" parameter on "Export-PSMTASTSDomainsFromExo" and "Test-PSMTASTSConfiguration". But I recommend to not use an internal DNS Server, except you are sure that these records will be resolved by an external/public dns server or root hints.

Tasks for use: 
1. We will add a custom timeout to the functions to let the module user know earlier, that the DNS Server is not available and suggest using the DNSServer parameter.
2. The DNSServer parameter has differencing names on "Export-PSMTASTSDomainsFromExo" and "Test-PSMTASTSConfiguration". Will be adjusted.

**Comment by jklotzsche-msft** [comment]
- Added new, internal function "Resolve-PSMTASTSDnsName" for resolving dns names
- Added -QuickTimeout Parameter for Resolve-DnsName in "Resolve-PSMTASTSDnsName" function to improve feedback time
- Adjusted DnsServer parameter for all functions to be the same --> -DnsServer
